# Generated by Codex on 2026-04-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_uuid', models.CharField(max_length=64, unique=True, verbose_name='Runner UUID')),
                ('name', models.CharField(max_length=200, verbose_name='执行器名称')),
                ('hostname', models.CharField(blank=True, max_length=255, verbose_name='主机名')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='平台')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线')], default='online', max_length=20, verbose_name='状态')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='附加信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_local_runners', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': 'UI 本地执行器',
                'verbose_name_plural': 'UI 本地执行器',
                'db_table': 'ui_local_runners',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='execution_mode',
            field=models.CharField(choices=[('server', '服务器执行'), ('local', '本地执行')], default='server', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='assigned_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_executions', to='ui_automation.localrunner', verbose_name='指派执行器'),
        ),
    ]
