# Generated by Django 4.2.7 on 2026-04-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0003_local_runner_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Folder Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_test_case_folders', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_folders', to='ui_automation.uiproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'UI Test Case Folder',
                'verbose_name_plural': 'UI Test Case Folders',
                'db_table': 'ui_test_case_folders',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='ui_automation.testcasefolder', verbose_name='Folder'),
        ),
        migrations.AddConstraint(
            model_name='testcasefolder',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='ui_test_case_folder_unique_name'),
        ),
    ]
