# Generated by Codex on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0010_alter_testcasestep_action_type_refresh_current_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseexecution',
            name='run_identifier',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='执行批次标识'),
        ),
        migrations.AddField(
            model_name='testcaseexecution',
            name='scheduled_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_executions', to='ui_automation.uischeduledtask', verbose_name='所属定时任务'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='assigned_runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='ui_automation.localrunner', verbose_name='本地执行器'),
        ),
        migrations.AddField(
            model_name='uischeduledtask',
            name='execution_mode',
            field=models.CharField(choices=[('server', '服务器执行'), ('local', '本地执行')], default='server', max_length=20, verbose_name='执行位置'),
        ),
    ]
