# Generated by Django 4.2.7 on 2026-05-06 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0012_ai_test_case_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITestCaseGenerationSkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Category Name')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'UI AI Test Case Generation Skill Category',
                'verbose_name_plural': 'UI AI Test Case Generation Skill Categories',
                'db_table': 'ui_ai_test_case_generation_skill_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AITestCaseGenerationSkillModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Module Name')),
                ('code', models.CharField(max_length=160, unique=True, verbose_name='Module Code')),
                ('module_type', models.CharField(choices=[('global', 'Global'), ('page', 'Page'), ('business_flow', 'Business Flow'), ('repair', 'Repair')], default='business_flow', max_length=32, verbose_name='Module Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('summary', models.TextField(blank=True, verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Keywords')),
                ('intents', models.JSONField(blank=True, default=list, verbose_name='Intents')),
                ('pages', models.JSONField(blank=True, default=list, verbose_name='Pages')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('max_prompt_chars', models.IntegerField(default=4000, verbose_name='Max Prompt Characters')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='ui_automation.aitestcasegenerationskillcategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_ai_generation_skill_modules', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'UI AI Test Case Generation Skill Module',
                'verbose_name_plural': 'UI AI Test Case Generation Skill Modules',
                'db_table': 'ui_ai_test_case_generation_skill_modules',
                'ordering': ['-priority', 'module_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AITestCaseGenerationSkillDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='ui_automation.aitestcasegenerationskillmodule', verbose_name='Depends On')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ui_automation.aitestcasegenerationskillmodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'UI AI Test Case Generation Skill Dependency',
                'verbose_name_plural': 'UI AI Test Case Generation Skill Dependencies',
                'db_table': 'ui_ai_test_case_generation_skill_dependencies',
            },
        ),
        migrations.CreateModel(
            name='AITestCaseGenerationSkillTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword'), ('regex', 'Regex'), ('intent', 'Intent'), ('page', 'Page'), ('entity', 'Entity')], default='keyword', max_length=32, verbose_name='Trigger Type')),
                ('value', models.CharField(max_length=500, verbose_name='Value')),
                ('weight', models.IntegerField(default=50, verbose_name='Weight')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='ui_automation.aitestcasegenerationskillmodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'UI AI Test Case Generation Skill Trigger',
                'verbose_name_plural': 'UI AI Test Case Generation Skill Triggers',
                'db_table': 'ui_ai_test_case_generation_skill_triggers',
                'ordering': ['module', '-weight', 'trigger_type', 'value'],
                'indexes': [models.Index(fields=['trigger_type', 'is_active'], name='ui_ai_test__trigger_ceb6fc_idx')],
                'unique_together': {('module', 'trigger_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AITestCaseGenerationSkillExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(blank=True, verbose_name='Source Text')),
                ('detected_intents', models.JSONField(blank=True, default=list, verbose_name='Detected Intents')),
                ('detected_entities', models.JSONField(blank=True, default=dict, verbose_name='Detected Entities')),
                ('selected_modules', models.JSONField(blank=True, default=list, verbose_name='Selected Modules')),
                ('prompt_chars', models.IntegerField(default=0, verbose_name='Prompt Characters')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Warnings')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_ai_generation_skill_execution_logs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_skill_execution_logs', to='ui_automation.uiproject', verbose_name='Project')),
                ('root_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='ui_automation.aitestcasegenerationskill', verbose_name='Root Skill')),
            ],
            options={
                'verbose_name': 'UI AI Test Case Generation Skill Execution Log',
                'verbose_name_plural': 'UI AI Test Case Generation Skill Execution Logs',
                'db_table': 'ui_ai_test_case_generation_skill_execution_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='ui_ai_test__project_1c5d51_idx'), models.Index(fields=['root_skill', '-created_at'], name='ui_ai_test__root_sk_81e747_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aitestcasegenerationskillmodule',
            index=models.Index(fields=['module_type', 'is_active'], name='ui_ai_test__module__e789b1_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestcasegenerationskillmodule',
            index=models.Index(fields=['priority'], name='ui_ai_test__priorit_5b2f97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aitestcasegenerationskilldependency',
            unique_together={('module', 'depends_on')},
        ),
    ]
