# Generated by Django 4.2.7 on 2026-04-21 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class SafeAddField(migrations.AddField):
    """Skip DB changes when a partially-applied test DB already has the field/table."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))
            if field.many_to_many:
                through_table = field.remote_field.through._meta.db_table
                if through_table in existing_tables:
                    return
            elif table_name in existing_tables:
                existing_columns = {
                    column.name
                    for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
                }
                if field.column in existing_columns:
                    return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAddIndex(migrations.AddIndex):
    """Skip DB index creation when the target index already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))
            if table_name not in existing_tables:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
                return
            constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
            if self.index.name in constraints:
                return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class SafeAlterUniqueTogether(migrations.AlterUniqueTogether):
    """Skip DB constraint creation when the requested unique set already exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table
        target_sets = {
            tuple(sorted(model._meta.get_field(field_name).column for field_name in item))
            for item in (self.unique_together or set())
        }

        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))
            if table_name not in existing_tables:
                super().database_forwards(app_label, schema_editor, from_state, to_state)
                return
            constraints = schema_editor.connection.introspection.get_constraints(cursor, table_name)
            existing_unique_sets = {
                tuple(sorted(info.get('columns') or ()))
                for info in constraints.values()
                if info.get('unique') and info.get('columns')
            }
            if target_sets and target_sets.issubset(existing_unique_sets):
                return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0001_initial'),
    ]

    operations = [
        SafeAddField(
            model_name='apptestsuite',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_app_test_suites',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAddField(
            model_name='apptestsuite',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='test_suites',
                to='app_automation.appproject',
                verbose_name='Project',
            ),
        ),
        SafeAddField(
            model_name='apptestsuite',
            name='test_cases',
            field=models.ManyToManyField(
                blank=True,
                through='app_automation.AppTestSuiteCase',
                to='app_automation.apptestcase',
                verbose_name='Test Cases',
            ),
        ),
        SafeAddField(
            model_name='apptestexecution',
            name='device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='executions',
                to='app_automation.appdevice',
                verbose_name='Device',
            ),
        ),
        SafeAddField(
            model_name='apptestexecution',
            name='test_case',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='executions',
                to='app_automation.apptestcase',
                verbose_name='Test Case',
            ),
        ),
        SafeAddField(
            model_name='apptestexecution',
            name='test_suite',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='executions',
                to='app_automation.apptestsuite',
                verbose_name='Test Suite',
            ),
        ),
        SafeAddField(
            model_name='apptestexecution',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='app_test_executions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        SafeAddField(
            model_name='apptestcase',
            name='app_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='test_cases',
                to='app_automation.apppackage',
                verbose_name='App Package',
            ),
        ),
        SafeAddField(
            model_name='apptestcase',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_app_test_cases',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAddField(
            model_name='apptestcase',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='test_cases',
                to='app_automation.appproject',
                verbose_name='Project',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='app_package',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scheduled_tasks',
                to='app_automation.apppackage',
                verbose_name='App Package',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='created_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='device',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scheduled_tasks',
                to='app_automation.appdevice',
                verbose_name='Device',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='scheduled_tasks',
                to='app_automation.appproject',
                verbose_name='Project',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='test_case',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scheduled_tasks',
                to='app_automation.apptestcase',
                verbose_name='Test Case',
            ),
        ),
        SafeAddField(
            model_name='appscheduledtask',
            name='test_suite',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='scheduled_tasks',
                to='app_automation.apptestsuite',
                verbose_name='Test Suite',
            ),
        ),
        SafeAddField(
            model_name='appproject',
            name='members',
            field=models.ManyToManyField(
                blank=True,
                related_name='app_projects',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Members',
            ),
        ),
        SafeAddField(
            model_name='appproject',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_app_projects',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Owner',
            ),
        ),
        SafeAddField(
            model_name='apppackage',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_app_package_names',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAddField(
            model_name='appnotificationlog',
            name='task',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notification_logs',
                to='app_automation.appscheduledtask',
                verbose_name='Task',
            ),
        ),
        SafeAddField(
            model_name='appelement',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_app_elements',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAddField(
            model_name='appelement',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='elements',
                to='app_automation.appproject',
                verbose_name='Project',
            ),
        ),
        SafeAddField(
            model_name='appdevice',
            name='locked_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='locked_app_devices',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Locked By',
            ),
        ),
        SafeAddField(
            model_name='appcomponentpackage',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='created_app_packages',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Created By',
            ),
        ),
        SafeAlterUniqueTogether(
            name='apptestsuitecase',
            unique_together={('test_suite', 'test_case')},
        ),
        SafeAddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['status'], name='app_test_ex_status_9ca315_idx'),
        ),
        SafeAddIndex(
            model_name='apptestexecution',
            index=models.Index(fields=['-created_at'], name='app_test_ex_created_05ebca_idx'),
        ),
        SafeAddIndex(
            model_name='apppackage',
            index=models.Index(fields=['package_name'], name='app_package_package_555fb1_idx'),
        ),
        SafeAddIndex(
            model_name='apppackage',
            index=models.Index(fields=['name'], name='app_package_name_cecc0d_idx'),
        ),
        SafeAddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['status'], name='app_notific_status_b1a744_idx'),
        ),
        SafeAddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['notification_type'], name='app_notific_notific_b8d115_idx'),
        ),
        SafeAddIndex(
            model_name='appnotificationlog',
            index=models.Index(fields=['created_at'], name='app_notific_created_35637c_idx'),
        ),
        SafeAddIndex(
            model_name='appelement',
            index=models.Index(fields=['element_type'], name='app_element_element_c563e9_idx'),
        ),
        SafeAddIndex(
            model_name='appelement',
            index=models.Index(fields=['name'], name='app_element_name_0cb360_idx'),
        ),
        SafeAddIndex(
            model_name='appelement',
            index=models.Index(fields=['is_active'], name='app_element_is_acti_772d00_idx'),
        ),
        SafeAddIndex(
            model_name='appdevice',
            index=models.Index(fields=['status'], name='app_devices_status_9e09a1_idx'),
        ),
        SafeAddIndex(
            model_name='appdevice',
            index=models.Index(fields=['device_id'], name='app_devices_device__1b1f25_idx'),
        ),
    ]
