# Generated by Django 4.2.7 on 2026-07-17 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_automation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcomponentpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_packages', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='appdevice',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_app_devices', to=settings.AUTH_USER_MODEL, verbose_name='锁定用户'),
        ),
        migrations.AlterField(
            model_name='appelement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_elements', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='appelement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='appnotificationlog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='app_automation.appscheduledtask', verbose_name='关联任务'),
        ),
        migrations.AlterField(
            model_name='apppackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_package_names', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='app_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员'),
        ),
        migrations.AlterField(
            model_name='appproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_app_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='app_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apppackage', verbose_name='应用包名'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.appdevice', verbose_name='执行设备'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AlterField(
            model_name='appscheduledtask',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='app_automation.apptestsuite', verbose_name='测试套件'),
        ),
        migrations.AlterField(
            model_name='apptestcase',
            name='app_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='app_automation.apppackage', verbose_name='应用包名'),
        ),
        migrations.AlterField(
            model_name='apptestcase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='apptestcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.appdevice', verbose_name='执行设备'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='test_suite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='app_automation.apptestsuite', verbose_name='所属套件'),
        ),
        migrations.AlterField(
            model_name='apptestexecution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_test_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行用户'),
        ),
        migrations.AlterField(
            model_name='apptestsuite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_test_suites', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='apptestsuite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_suites', to='app_automation.appproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='apptestsuite',
            name='test_cases',
            field=models.ManyToManyField(blank=True, through='app_automation.AppTestSuiteCase', to='app_automation.apptestcase', verbose_name='测试用例'),
        ),
    ]
